### ISSUE TITLE
Skeleton crashes

### ISSUE THREAD

**Issue by stefankinell** [thangqd/becagis#2]
Hi,
Nice set of tools, looks promissing! But the skeleton tool keeps crashing on me. I get the following crash report:

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00001224 (most recent call first):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 72 in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\core\Processing.py", line 187 in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
Windows fatal exception:   File access violation"

C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\tools\general.py", line 108 in run
  File "C:\Users/web/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\becagis\becagislibrary\voronoi.py", line 76 in skeleton
    voronoipolygon = processing.run('qgis:voronoipolygons', parameters4)
  File "C:\Users/web/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\becagis\processing_provider\Vect_Skeleton.py", line 221 in processAlgorithm
    mem_layers.append(skeleton(selected_feature, unique_field, density, tolerance))

Current thread 0x00004b20 (most recent call first):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 395 in executeAlgorithm
    dlg.exec_()
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 234 in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

**Comment by stefankinell** [comment]
This is one example file that I have problem with.
[buffert_18A003_61675_3975_25.laz_c3g.zip](https://github.com/thangqd/becagis/files/10185715/buffert_18A003_61675_3975_25.laz_c3g.zip)

**Comment by thangqd** [comment]
Thank you @stefankinell for your feedback
Please upgrade your BecaGIS plugin to the latest version (23.2.18) to fix your reported error. Due to the performance reason, Skeleton function currently supports up to 20 features each time. Please let me know if you have any issues.

**Comment by stefankinell** [comment]
Thanks for you reply and update,

When you say 20 features - does that mean in each polygon there can only be 20 corners/points. Or the skeleton? Or do you mean it can handle 20 polygons at a time as input? Regardless of that I think I might run into problems since my input files contains easily thousands of polygons and each polygon can have more than 1000 vertexes.

**Comment by thangqd** [comment]
1 to 20 polygons at a time, not vertices
