### ISSUE TITLE
QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 

### ISSUE THREAD

**Issue by louwers** [thangqd/becagis#3]
Getting this error on startup:

An error has occurred while executing Python code: 

TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/Users/bart/Library/Application Support/QGIS/QGIS3/profiles/bart/python/plugins/becagis/processing_provider/Vect_DirectionalMerge.py", line 122, in initAlgorithm
    QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

Python version: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:52:50) [Clang 16.0.6 ] 
QGIS version: 3.36.0-Maidenhead Maidenhead, exported

**Comment by qsavoye** [comment]
replace 
```python
self.addParameter(
            QgsProcessingParameterNumber(
                self.ANGLE,
                self.tr('Tolerance in degrees', 'Ngưỡng (độ)'),
                type=1,
                defaultValue = 30
                )
            )
```
by 
```python
self.addParameter(
            QgsProcessingParameterNumber(
                self.ANGLE,
                self.tr('Tolerance in degrees', 'Ngưỡng (độ)'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue = 30
                )
            )
```

in file /QGIS/QGIS3/profiles/bart/python/plugins/becagis/processing_provider/Vect_DirectionalMerge.py
