### ISSUE TITLE
Support of the graphical modeler in QGIS

### ISSUE THREAD

**Issue by KonstiDE** [thangqd/becagis#4]
Dear team,

I am wondering why the BecaGIS algorithms as Skeleton, Isolation or "Merge lines in direction" do not support the QGIS graphical modeler as they do not function properly within it.

As an example, I was trying to skeletonize a bucnh of polygons within a pipeline, pyping out a single dissolved polygon.

I thought that the problem would just occur because no features are selected when outputting a layer in the graphical modeler. Moreover, this is not possible.

The most simple but usual strong solution is just to modify the plugin and so I want ahead to just select all features by `input_layer.selectByExpression("$id")` real quick below the feature count restriction in `Vect_Skeleton.py`, line 192. 

However, it just yields in an empty result:
<img width="739" alt="snipping" src="https://github.com/user-attachments/assets/31dcbd74-532c-45ff-8ef1-4e1f3984fa04">

For reproducability, just load the appended tif and execute the appended model onto it. The dissolved layer works but no skeleton layer is generated. In a second step, manually execute "Skeleton" from Beca-GIS onto the dissolved layer, this works.

Materials: 
[materials.zip](https://github.com/user-attachments/files/16627455/materials.zip)

I think the plugin would really benefit from a modeler support since post-processing needs to be applied as well...

**Comment by thangqd** [comment]
Please update to the latest version of BecaGIS @KonstiDE . Thanks

**Comment by thangqd** [comment]
Please update the latest version of BecaGIS @KonstiDE . Thanks
